
INSERT INTO posts (Title, Entry, DateTime) VALUES
('The Wonderfully Weird Tiger King','Tiger King Murder, Mayhem and Madness is a 2020 American true crime documentary miniseries about the life of zookeeper Joe Exotic. It was released on Netflix on March 20, 2020.The series focuses on the small but deeply interconnected society of big cat conservationists such as Carole Baskin, owner of Big Cat Rescue, and collectors such as Exotic, whom Baskin accuses of abusing and exploiting wild animals. A special hosted by Joel McHale was released on April 12, 2020, with McHale interviewing several of the stars about Exotic and the series itself.
The series received acclaim from critics, and according to Nielsen ratings, was watched by 34.3 million people over its first ten days of release,ranking as one of Netflixs most successful releases to date.The series explores the little-known, deeply interconnected society of big cat conservationists and collectors in America,and the private zoos and sanctuaries they have set up for these unusual and deadly animals. The primary subject is Joe Exotic, the eccentric owner of the G.W. Zoo in Wynnewood, Oklahoma, and his bitter years-long feud with Carole Baskin, CEO of Big Cat Rescue in Tampa,
Florida. Baskin presents herself as an animal rights activist whose mission is to provide a sanctuary for big cats raised in captivity, but Joe Exotic maintains that she is simply a rival zookeeper whose aim is to eliminate her competition. The two exchange threatening videos, 
legal allegations, protests, and targeted harassment campaigns, in which PETA and the United States Fish and Wildlife Service become involved. Joe Exotic goes so far as to allege that Baskin murdered her second husband Don Lewis, who has been missing since 1997.Joe Exotics personal life becomes a subject of interest, particularly his unofficial three-way same-sex marriage to Travis Maldonado and John Finlay and his subsequent relationships with them and future husband Dillon Passage. His 2016 run for President of the United States and 2018 run for Governor of Oklahoma are documented with the assistance of his campaign manager, Joshua Dial. Producer Rick Kirkham recounts the rise and fall of "Joe Exotic TV", a sort of podcast that Kirkham was hoping to develop into a TV series until his footage is mysteriously destroyed. The series then records the events leading up to Joe Exotics conviction under federal murder-for-hire statutes when it comes to light that he paid a hitman to murder Baskin;
his conviction also includes violations of the Lacey Act and Endangered Species Act, and results in a 22-year federal prison sentence.Other characters from the exotic animal community are introduced, including Bhagavan Antle, an animal breeder accused of leading a personality cult; Mario Tabraue, a former drug lord who is involved in animal trafficking; Jeff Lowe, a Las Vegas playboy to whom Joe Exotic turns over his zoo for legal reasons; and James Garretson, who became a confidential informant for the federal government and a key figure in making the case against Joe Exotic.Former G.W. Zoo employees such as manager John Reinke and animal wrangler Saff Saffery conclude the series by commenting that the animals themselves were forgotten amongst all the interpersonal fighting, and that no party has truly come out victorious.','2020-04-21 13:45:00'),
('Books to lift your mood','Eleanor leads a simple life. Wearing the same clothes each day to work, eating the same thing at lunch, and buying the same two bottles of vodka to drink each weekend.Happy, nothing is missing from her carefully timetabled life. Except, sometimes, everything. As one simple act of kindness shatters the walls.Eleanor has built around her, she must learn to navigate the world everyone else seems to take for granted.Exploring the idea that change can be good or bad, but is always better than just being fine. An uplifting, gentle and honest story infused with humour and realism that reminds us that those we know superficially may, in fact,be living their lives in a completely different context to our own.','2020-04-21 13:45:00'),
('The Banana Bread Phenomenon', 'It seems bread has been the isolation staple and I can see why it is super easy to make and delicious. This is my favorite banana bread recipe. Its the recipe that comes to mind first when I have leftover spotty bananas on the counter.Ive tried many many many banana bread recipes and this one is my very favorite.What makes this one so good.Well really its up to you what extras do you want to add in Walnuts, chocolate chips you name it. Did you know you can use your electric mixer to mash bananas. Break or slice the spotty bananas into large pieces and place in the bowl of your stand mixer or use a regular mixing bowl and your hand mixer.Begin beating on low, then gradually increase to medium high speed as the bananas break down into mashed banana. You can use this bowl for the rest of the banana bread ingredients.Once the banana is masehd add all of your other ingredients and give it a good stir. Place in a loaf tin and back for 35minutes, and thats that.','2020-04-21 13:45:00');


INSERT INTO categories (PostID, Hashtag) VALUES
('31', '#Entertainment'),
('32', '#Entertainment'),
('33', '#FoodandDrink');


